#!/usr/bin/env bash
#
# Generates polkadot-app/CIKeys.generated.swift from build-time configuration.
#
# Values are resolved from (highest priority first):
#   1. polkadot-app/env-vars.sh and the current environment (secrets & overrides)
#   2. the inline placeholder defaults below (committed, non-secret)
#
# Run automatically by Scripts/setup-secrets.sh and as an Xcode scheme
# pre-action, or manually whenever the configuration changes:
#
#     ./Scripts/inject-keys.sh
#
set -euo pipefail

export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"

WORK_DIR="$ROOT_DIR/polkadot-app"
ENV_VARS_FILE="$WORK_DIR/env-vars.sh"
OUT_FILE="$WORK_DIR/CIKeys.generated.swift"

# Secrets and local overrides (gitignored). Anything left unset falls back to
# the placeholder defaults inlined below; empty secrets disable the feature.
if [ -f "$ENV_VARS_FILE" ]; then
    # shellcheck disable=SC1090
    source "$ENV_VARS_FILE"
fi

cat > "$OUT_FILE" <<EOF
// Auto-generated by Scripts/inject-keys.sh — do not edit manually.
//
// Secrets come from polkadot-app/env-vars.sh / the build environment.
// Non-secret defaults are inlined in Scripts/inject-keys.sh.
import Foundation

enum CIKeys {
    // Secrets (empty values disable the related feature)
    static let w3sAuthKeyHex = "${W3S_AUTH_KEY:-}"
    static let posthogAPIKey = "${POSTHOG_API_KEY:-}"
    static let sentryDSN = "${SENTRY_DSN:-}"
    static let meldBasicAuthToken = "${MELD_BASIC_AUTH_TOKEN:-}"

    // Brand links (placeholders — replace with your own)
    static let termsOfUseLink = "${TERMS_OF_USE_LINK:-https://example.com/terms}"
    static let privacyPolicyLink = "${PRIVACY_POLICY_LINK:-https://example.com/privacy}"
    static let contactEmail = "${CONTACT_EMAIL:-support@example.com}"

    // Support recipients for in-app mail drafts (replace with your own inbox)
    static let reportIssueEmail = "${REPORT_ISSUE_EMAIL:-support@example.com}"
    static let logsEmail = "${LOGS_EMAIL:-support@example.com}"

    // Endpoints (generic public services kept as real, the rest are placeholders)
    static let gameResultsFallbackURL = "${GAME_RESULTS_FALLBACK_URL:-https://your-game-results.example/}"
    static let meldBaseURL = "${MELD_BASE_URL:-https://api.meld.io/}"
    static let coingeckoBaseURL = "${COINGECKO_BASE_URL:-https://api.coingecko.com/api/v3}"
    static let posthogHost = "${POSTHOG_HOST:-https://eu.i.posthog.com}"
}
EOF

echo "Generated $OUT_FILE"
