name: Update signing data

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *" # 10:00 AM every day

jobs:
  update_signing_data:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6

      - name: Setup iOS Environment
        uses: ./.github/actions/install
        with:
          match_auth_required: "true"
          match_repository_pat: ${{ secrets.FASTLANE_RW_PAT }}

      - name: Update signing data
        run: bundle exec fastlane update_signing_data
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_BASE64: ${{ secrets.ASC_KEY_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
